FirstWebAppMVC/Models/ErrorViewModel.cs
namespace FirstWebAppMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FirstWebAppMVC/ViewModels/AnimalListViewModel.cs
namespace FirstWebAppMVC.ViewModels
{
    public class AnimalListViewModel
    {
        public List<AnimalListItemViewModel> Animals { get; set; }

        public class AnimalListItemViewModel
        {
            public string Name { get; set; }
            public string Latin_Name { get; set; }
            public string Habitat { get; set; }
        }
    }

   
}

FirstWebAppMVC/ViewModels/ProductIndexViewModel.cs
namespace FirstWebAppMVC.ViewModels
{
    public class ProductIndexViewModel
    {
        public class ProductViewModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
        public List<ProductViewModel> Items { get; set; }
    }

    
}

FirstWebAppMVC/Controllers/AnimalController.cs
using FirstWebAppMVC.Services;
using FirstWebAppMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FirstWebAppMVC.Controllers
{
    public class AnimalController : Controller
    {
        private IAnimalService _animalService;

        public AnimalController(IAnimalService animalService)
        {
            _animalService = animalService;
        }
        public IActionResult Index()
        {
            var model = new AnimalListViewModel();
            model.Animals = _animalService.GetLatest().Select(a => new
                AnimalListViewModel.AnimalListItemViewModel
            {
                Name = a.Name,
                Latin_Name = a.Latin_Name,
                Habitat = a.Habitat,
            }
                ).ToList();

            return View(model);
        }

        //public IActionResult Index()
        //{
        //    var model = new KrisInfoListViewModel();
        //    model.Items = _krisInfoService.GetLatest().Select(e => new
        //        KrisInfoListViewModel.KrisInfoListItemViewModel
        //    {
        //        Headline = e.Headline,
        //        Identitifer = e.Identitifer
        //    }
        //        ).ToList();




        //    return View(model);
        //}
    }
}

FirstWebAppMVC/Controllers/HomeController.cs
using FirstWebAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstWebAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FirstWebAppMVC/Controllers/ProductController.cs
using FirstWebAppMVC.Data;
using FirstWebAppMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FirstWebAppMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        /*
            - här skriver vi kod som "KONTROLLERAR FLÖDET" vad som ska hända
            - hämta från databas osv
            - validera
            - lägg properties i "Model"
        */

        public IActionResult Index()
        {
            var model = new ProductIndexViewModel
            {
                Items = _context.Products.Select(i => new ProductIndexViewModel.ProductViewModel
                {
                    Id = i.Id,
                    Name = i.Name,
                }).ToList()
            };
            

            return View(model);
        }
    }
}

FirstWebAppMVC/Views/Animals/Index.cshtml
@model FirstWebAppMVC.ViewModels.AnimalListViewModel

@{
    ViewData["Title"] = "Animals";
}

<h1>All Animals</h1>
<ul>
    @foreach (var animal in Model.Animals)
    {
        <li>
            <a asp-controller="Animal" asp-route-id="@animal.Name"></a>
        </li>
        <li>
            <a asp-controller="Animal" asp-route-id="@animal.Latin_Name"></a>
        </li>
        <li>
            <a asp-controller="Animal" asp-route-id="@animal.Habitat"></a>
        </li>
    }
</ul>

FirstWebAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FirstWebAppMVC/Views/Product/Index.cshtml
@model FirstWebAppMVC.ViewModels.ProductIndexViewModel

@{
    ViewData["Title"] = "Products";
}

<h1>Products</h1>

<ul>
    @foreach(var product in Model.Items)
    {
        <li>
            <a asp-controller="Product" asp-action="Edit" asp-route-id="@product.Id">
                @product.Name
            </a>
        </li>
    }
</ul>

FirstWebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstWebAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstWebAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstWebAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FirstWebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>